#!/bin/bash
#PBS -S /bin/bash
#PBS -l partition=bigmem,nodes=1:ppn=48,walltime=24:00:00
#PBS -A ACF-UTK0011
#PBS -M wbrewer5@vols.utk.edu
#PBS -m abe
#PBS -o /lustre/haven/user/wbrewer5/macrosiphum/flye/log/
#PBS -e /lustre/haven/user/wbrewer5/macrosiphum/flye/error/
#PBS -N pandora_flye
#PBS -n 

cd $PBS_O_WORKDIR

module load anaconda3
source $ANACONDA3_SH
conda activate flye

flye --nano-raw /lustre/haven/user/wbrewer5/macrosiphum/raw/macrosiphum_nanopore.fastq.gz \
-o /lustre/haven/user/wbrewer5/macrosiphum/flye/output/ \
-g 800m \
-i 0 \

